repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        verbose: true
  
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        verbose: true
        additional_dependencies:
          - Flake8-pyproject
          - git+https://github.com/5cat/flake8-print@89ebeb6